name = "backend"
main = "src/index.ts"
compatibility_date = "2025-08-04"

# Uncomment if you need Node.js compatibility
compatibility_flags = ["nodejs_compat"]

[vars]
DATABASE_URL=""
JWT_SECRET = ""

